<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <ProjectReference Include="../PlataformaDigital.Modules.People.Domain/PlataformaDigital.Modules.People.Domain.csproj" />
    <ProjectReference Include="../../PlataformaDigital.BuildingBlocks/PlataformaDigital.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
